type User {
  id: ID!
  name: String!
  username: String!
  lastname: String!
  age: Int
  bio: String
  avatar: String
  posts: [Post!]
}


type Post {
  id: Int!
  post: String!
  commentaries: [Commentary!]
}

scalar Date

type Commentary {
  commentary: String
  date: Date
}

type Query {
  user(id: ID!): [User!]! @isAuthenticated
}

type Mutation {
  createAccount(data: userInput!): User!
  inactiveAccount(id: Int!): User! @isAuthenticated
  login(data: login!): authPayloadUser!
  uploadProfile(userId: ID!, data: userProfileInput!): User! @isAuthenticated
}

input login {
  username: String!
  password: String!
}

input userProfileInput {
  age: Int!
  bio: String!
  imgProfile: String!
}

type authPayloadUser {
  token: String!
  user: User!
}

input userInput {
  name: String!
  lastname: String!
  username: String!
  password: String!
}

directive @isAuthenticated on QUERY | FIELD | FIELD_DEFINITION
