scalar Date

type User {
  id: ID!
  name: String!
  username: String!
  lastname: String!
  birthDay: Date
  bio: String
  avatar: String
  posts: [Post!]
}


type Query {
  user(username: String!): [User!]! @isAuthenticated
}

type Mutation {
  createAccount(data: userInput!): User!
  inactiveAccount(id: Int!): User! @isAuthenticated
  login(data: login!): authPayloadUser!
  uploadProfile(userId: ID!, data: userProfileInput!): User! @isAuthenticated
}

input login {
  username: String!
  password: String!
}

input userProfileInput {
  birthDay: Date!
  bio: String!
  imgProfile: String!
}

type authPayloadUser {
  token: String!
  user: User!
}

input userInput {
  name: String!
  lastname: String!
  username: String!
  password: String!
  birthDay: Date!
}

directive @isAuthenticated on QUERY | FIELD | FIELD_DEFINITION
