type Post {
  id: ID!
  post: String!
  commentaries: [Commentary!]
  author: User!
}

scalar Date

type Commentary {
  commentary: String!
  author: [User!]
}

type Query {
  getPost(id: ID): [Post!]
}

type Mutation {
    createPost(data: PostInput!): Post!
    createCommentary(data: CommentaryInput!): Commentary!
}


input PostInput {
    author: ID!
    post: String!
}

input CommentaryInput {
  post: ID!
  commentary: String!
  author: ID!
}